# Generated by Django 5.0.3 on 2024-03-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=64, verbose_name='标题')),
                ('detail', models.TextField(verbose_name='详细信息')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('comment', models.TextField(verbose_name='评论')),
                ('uid', models.IntegerField(verbose_name='UID')),
            ],
        ),
    ]
